apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: zenithworkssimplegoapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zenithworkssimplegoapp 
    spec:
      containers:
        - name: zenithworkssimplegoapp 
          image: raireg1.azurecr.io/zenithworkssimplegoapp
          ports:
          - containerPort: 80