apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsdemo 
    spec:
      containers:
        - name: dsmsdemo 
          image: desattiracr.azurecr.io/dsmsdemo
          ports:
          - containerPort: 80